# This is a basic workflow to help you get started with Actions

name: Vault secrets

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - develop
      - master
    tags:
      - '*'
  pull_request:
    branches: [ master ]

jobs:
    build:
        # ...
        runs-on: ubuntu-latest
        steps:
            # ...
            - name: Import Secrets
              uses: hashicorp/vault-action
              with:
                url: https://ele.roava.io:8200/
                token: ${{ secrets.VaultToken }}
                caCertificate: ${{ secrets.VAULTCA }}
                secrets: |
                    roava/secrets/pulsar PULSAR_URL | PULSAR_URL ;
                    roava/secrets/onfido onfido_API_token | onfido_API_token ;
                    

            - name: Sensitive Operation
              run: "my-cli --token '${{ steps.secrets.outputs.onfido_API_token }}'"
            # ...
