# This is a basic workflow to help you get started with Actions

name: Vault secrets

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - develop
      - master
    tags:
      - '*'
  pull_request:
    branches: [ master ]


jobs:
    build:
        # ...
        runs-on: ubuntu-latest
        steps:
            # ...
            - name: Import Secrets
              uses: hashicorp/vault-action@master
              with:
                url: ${{ secrets.VaultAddress }}
                token: ${{ secrets.VaultToken }}
                caCertificate: ${{ secrets.VAULTCA }}
                tlsSkipVerify: true
                secrets: |
                    roava/secrets/pulsar PULSAR_URL | PULSAR_URL ;
                    roava/secrets/onfido ONFIDO_SERVICE | ONFIDO_SERVICE ;
                    

            - name: Run a multi-line script
              run: |
                echo $PULSAR_URL 
                  # ...
